# Generated by Django 2.2.3 on 2024-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilito', '0004_product_image'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='facilito.Product'),
        ),
    ]
